package com.lmsProject.lms.enums;

public enum CourseCategory {
    PROGRAMMING,
    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    DATA_SCIENCE,
    MACHINE_LEARNING,
    CLOUD_COMPUTING,
    CYBER_SECURITY,
    ARTIFICIAL_INTELLIGENCE,
    DEVOPS,
    DATABASES,
    SOFTWARE_ENGINEERING,
    GAME_DEVELOPMENT,
    DESIGN,
    BUSINESS,
    MARKETING,
    FINANCE,
    COMMUNICATION,
    PERSONAL_DEVELOPMENT,
    LANGUAGES,
    HEALTH_AND_FITNESS,
    MUSIC,
    EDUCATION,
    TEST_PREPARATION
}
